const DocItems = {
    book:{
        order:0, 
        icon:"img/book.png", 
        expand:true, 
        link:"/$/index.html", 
        to:"book_root"
    },
    chapter:{
        order:1, 
        icon:"img/book.png", 
        expand:true, 
        link:"/$/index.html", 
        to:"book_root"
    },
    page:{
        order:1, 
        icon:"img/book.png", 
        expand:true, 
        link:"/$/index.html", 
        to:"book_root"
    },
    keyword:{
        order:5, 
        icon:"img/item/page.png", 
        expand:false, 
        link:"/keyword.$.html", 
        to:"keywords_root"
    },
    primitive:{
        order:6, 
        icon:"img/item/block.png", 
        expand:false, 
        link:"/primitive.$.html", 
        to:"primitives_root"
    },
    crate:{
        order:10,
        icon:"img/item/crate.png",
        expand:true,
        link:"/$/index.html"
    },
    mod:{
        order:11, 
        icon:"img/item/mod.png", 
        expand:true, 
        link:"/$/index.html"
    },
    type:{
        order:12, 
        icon:"img/item/type.png", 
        link:"/type.$.html", 
        expand:false
    },
    struct:{
        order:13,
        icon:"img/item/struct.png", 
        link:"/struct.$.html", 
        expand:false
    },
    constant:{
        order:13,
        icon:"img/item/const.png", 
        link:"/constant.$.html", 
        expand:false
    },
    enum:{
        order:14, 
        icon:"img/item/enum.png", 
        link:"/enum.$.html", 
        expand:false
    },
    union:{
        order:15, 
        icon:"img/item/union.png", 
        link:"/union.$.html", 
        expand:false
    },
    trait:{
        order:16, 
        icon:"img/item/trait.png", 
        link:"/trait.$.html", 
        expand:false
    },
    fn:{
        order:17, 
        icon:"img/item/fn.png", 
        link:"/fn.$.html", 
        expand:false
    },
    macro:{
        order:18, 
        icon:"img/item/macro.png", 
        link:"/macro.$.html", 
        expand:false
    }
};